'((type . draft)
  (mode . autotools)
  (name . "zlib")
  (section . "libs")
  (description . "Compression and decompression routines")
  (options . "")
  (releases . (("1.2.7" . "http://www.zlib.net/zlib-1.2.7.tar.bz2"))))
