'((type . draft)
  (mode . autotools)
  (name . "psmisc")
  (section . "devel")
  (desription . "Programs for displaying information about running processes")
  (options . "")
  (releases . (("22.20" . "http://prdownloads.sourceforge.net/psmisc/psmisc-22.20.tar.gz"))))
