'((type         . draft)
  (mode         . autotools)
  (name         . "patch")
  (section      . "devel")
  (description  . "A program  for modifying or creating files by applying a “patch” file")
  (options      . "")
  (releases     . (("2.7.1" . "http://ftp.gnu.org/gnu/patch/patch-2.7.1.tar.xz"))))
