'((type . draft)
  (mode . autotools)
  (name . "autoconf")
  (section . "devel")
  (description . "Autoconf is an extensible package of M4 macros that \
produce shell scripts to automatically configure software source code packages.")
  (options . "")
  (releases . (("2.69" . "ftp://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz")
	       ("2.68" . "ftp://ftp.gnu.org/gnu/autoconf/autoconf-2.68.tar.xz")))
  (install-info . #t))
