'((type         . draft)
  (mode         . autotools)
  (name         . "tar")
  (section      . "apps")
  (description  . "An archiving program")
  (options      . "")
  (releases     . (("1.26" . "http://ftp.gnu.org/gnu/tar/tar-1.26.tar.bz2")))
  (install-info . #t)
  (pre-hook     . ("sed -i -e '/gets is a/d' gnu/stdio.in.h")))
