'((type . draft)
  (mode . autotools)
  (name . "mpc")
  (section . "libs")
  (description . "A library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result")
  (options . "")
  (releases . (("1.0.1" . "http://www.multiprecision.org/mpc/download/mpc-1.0.1.tar.gz")))
  (install-info . #t))
