'((type . draft)
  (mode . autotools)
  (name . "gmp")
  (section . "libs")
  (description . "The GMP package contains math libraries.")
  (options . "--enable-cxx")
  (releases . (("5.1.0" . "ftp://ftp.gmplib.org/pub/gmp-5.1.0/gmp-5.1.0.tar.xz")))
  (install-info . #t))
