'((type . draft)
  (mode . autotools)
  (name . "sed")
  (section . "apps")
  (description . "A stream editor")
  (options . "")
  (releases . (("4.2.2" . "http://ftp.gnu.org/gnu/sed/sed-4.2.2.tar.bz2")))
  (install-info . #t))
