'((type         . draft)
  (mode         . autotools)
  (name         . "make")
  (section      . "devel")
  (description  . "A program for compiling packages")
  (options      . "")
  (releases     . (("3.82" . "http://ftp.gnu.org/gnu/make/make-3.82.tar.bz2")))
  (patches      . (((name . "make-3.82-upstream_fixes-3")
	            (for-version . ("3.82")))))
  (install-info . #t))
