'((type         . draft)
  (mode         . autotools)
  (name         . "emacs-nox")
  (section      . "editors")
  (description  . "Emacs Meta Alt Control Shift")
  (options      . "--without-all")
  (releases     . (("24.3" . "http://ftpmirror.gnu.org/emacs/emacs-24.3.tar.xz")))
  (install-info . #t))
